version: '3'
services:

    #PHP Service
    base_app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: base_app
#        restart: unless-stopped
#        tty: true
        volumes:
            - ./:/var/www/base
        ports:
            - "80:80"
            - "6001:6001"
        working_dir: /var/www/base
        networks:
            - base_network
        links:
            -   base_db
    base_db:
        image: mariadb:latest
        container_name: base_db
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        networks:
            - base_network
        environment:
            MYSQL_DATABASE: base_db
            MYSQL_ROOT_PASSWORD: 123456
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
networks:
    base_network:
        driver: bridge

